openfile = open('Textfile.txt')
a = openfile.read()
print(a)
openfile.seek(0)
b = openfile.read()
print(b)
openfile.seek(0)
for line in open('Textfile.txt'):
    print(line)
writefile = open('Write.txt', 'w')
writefile.write('New line in the file')
writefile.seek(0)
c = writefile.read()
print(c)